filebeat:
    # image: docker.io/prima/filebeat
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes: 
     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
     - /var/log/nginx:/var/log/nginx
     - /var/log/messages:/var/log/messages
    # - ./logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
     - /etc/hosts:/etc/hosts
