zbx_srv:
    image: 192.168.254.211:5000/zabbix/zabbix-server-mysql
  #  links: 
  #     - zbx_agent
    environment:
       - DB_SERVER_HOST=192.168.254.110
       - MYSQL_USER=zabbix
       - MYSQL_DATABASE=zabbix
       - MYSQL_PASSWORD=zabbix 
       - DB_SERVER_ROOT_USER=zabbix
       - DB_SERVER_ROOT_PASS=zabbix
       - TZ＝'Asia/Shanghai' 
    ports:
       - 10051:10051 
    volumes:
       - /etc/localtime:/etc/localtime:ro 
       - ./zabbix-scripts:/usr/lib/zabbix 
       - ./zabbix:/etc/zabbix 
      # - ./docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh
    #net: host
    restart: always
zbx_web:
    image: 192.168.254.211:5000/zabbix/zabbix-web-nginx-mysql
    environment:
       - DB_SERVER_HOST=192.168.254.110
       - MYSQL_USER=zabbix
       - MYSQL_PASSWORD=zabbix
       - MYSQL_DATABASE=zabbix
       - ZBX_SERVER_HOST=192.168.254.113
       - PHP_TZ="Asia/Shanghai" 
       - TZ＝'Asia/Shanghai' 
    ports:
       - 8080:80 
       - 8443:443 
    volumes:
     #  - ./docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh
       - ./defines.inc.php:/usr/share/zabbix/include/defines.inc.php
    #net: host
    restart: always
zbx_agent:
    image: 192.168.254.211:5000/zabbix/zabbix-agent 
    #links: 
    #    - zbx_srv
    environment:
        - ZBX_HOSTNAME=zbx_srv_agent
        - ZBX_SERVER_HOST=172.17.0.2
        - ZBX_SERVER_PORT=10051 
        - TZ='Asia/Shanghai' 
    ports:
       - 10050:10050 
    volumes:
       - ./zabbix:/etc/zabbix
       - ./zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
    net: host
    privileged: true
    restart: always

