nginx:
  image: nginx

  environment:
    - TZ＝'Asia/Shanghai'

  volumes:
    - ./ngx_download/download.yunwei.edu.conf:/etc/nginx/conf.d/download.yunwei.edu.conf
    - ./nginxlog:/var/log/nginx
    - /export/download:/opt/download

  ports:
    - "80:80/tcp"
    - "443:443/udp"
  restart: always
