elk:
   image: sebp/elk
   ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
   volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d
      - ./tls/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt 
      - ./tls/logstash-beats.key:/etc/pki/tls/private/logstash-beats.key
