web:
  image: '192.168.100.222:5000/gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.yunwei.edu'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.yunwei.edu'
      gitlab_rails['gitlab_shell_ssh_port'] = 122
  ports:
    - '1180:80'
    - '1443:443'
    - '122:22'
  volumes:
    - '/opt/cmp_gitlab/gitlab/config:/etc/gitlab'
    - '/opt/cmp_gitlab/gitlab/logs:/var/log/gitlab'
    - '/opt/cmp_gitlab/gitlab/data:/var/opt/gitlab'
