version: '3'
services:

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
#    command: -H tcp://192.168.100.222:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - skynet
#      - SwamComposeNet
    
#networks:
#  SwamComposeNet:
#    driver: overlay
#    attachable: true

networks:
  skynet:
    external: true
volumes:
  portainer_data:
